name: practica-gitlab

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and extract artifacts from GitLab
        run: |
          curl -LJO "https://gitlab.com/api/v4/jobs/5926421123/artifacts?artifact_format=zip&artifact_type=archive"
          mv artifacts artifacts.rar
          unrar x artifacts.rar .
          ls
          echo "----------"
          echo "End of file"
          cp site/* gh-pages
          cp site/* .

      - name: Upload index.html to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: gh-pages/index.html

      - name: Print Content of gh-pages
        run: |
          ls -R gh-pages
          
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
