name: Deploy GitHub-Pages

on:
  workflow_run:
    workflows: ["practica_gitlab"]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and extract artifacts from GitLab
      run: |
        wget --quiet --output-document=artifacts.rar "https://gitlab.com/api/v4/jobs/5926421123/artifacts?artifact_format=zip&artifact_type=archive"
        unrar x artifacts.rar .
        cp site/* gh-pages
        cp site/* .

    - name: Print Content of gh-pages
      run: |
        ls -R gh-pages

    - name: Deploy to GitHub Pages
      run: |
        cd gh-pages
        git init
        git add .
        git commit -m "Deploy from GitHub Actions"
        git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
