name: Deploy GitHub-Pages

on:
  workflow_run:
    workflows: ["practica_gitlab"]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install grip

    - name: Download HTML from GitLab artifacts
      run: |
        wget --quiet --output-document=site/index.html "https://gitlab.com/api/v4/jobs/5926421123/artifacts/raw/site/index.html"

    - name: Deploy to GitHub Pages
      run: |
        cd site
        git init
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy from GitHub Actions"
        git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
