name: practica-gitlab

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts from GitLab
        run: |
          curl --location -o index.html "https://vs_uca_raulydavid.gitlab.io/-/practica_gitlab/-/jobs/5926421123/artifacts/site/index.html"
          ls -l    # Agregado para verificar si el archivo se descargó correctamente
          mkdir -p gh-pages
          cp index.html gh-pages/

      - name: Print Content of gh-pages
        run: |
          ls -R gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          publish_branch: main  # Cambia a la rama que desees utilizar
