name: practica-gitlab

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts from GitLab
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine64 wine32
          curl -O https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-xx.exe
          wine winrar-x64-xx.exe
          wine "C:\Program Files\WinRAR\WinRAR.exe" x artifacts.zip
          cp ./artifacts/site/* gh-pages

      - name: Print Content of gh-pages
        run: |
          ls -R gh-pages
          
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
