name: practica-gitlab

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts from GitLab
        run: |
          curl -LJO "https://gitlab.com/api/v4/jobs/5926421123/artifacts.zip" -o artifacts.zip
          ls -l    # Agregado para verificar si el archivo se descargó correctamente
          sudo apt-get install -y unzip
          unzip artifacts.zip -d artifacts
          ls -l artifacts  # Agregado para verificar el contenido de la carpeta "artifacts"
          cp -r artifacts/site/* gh-pages

      - name: Print Content of gh-pages
        run: |
          ls -R gh-pages
          
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
