name: practica-gitlab

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifacts from GitLab
        run: |
          curl --location -o index.html "https://vs_uca_raulydavid.gitlab.io/-/practica_gitlab/-/jobs/5926421123/artifacts/site/index.html"
          ls -l    # Agregado para verificar si el archivo se descargó correctamente
          mkdir -p gh-pages
          cp index.html gh-pages/

      - name: Print Content of gh-pages
        run: |
          ls -R gh-pages

      - name: Configure Git Identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git init
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push --force --quiet "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:gh-pages
